kind: Service
apiVersion: v1
metadata:
  name: nfs-service
spec:
  clusterIP: 10.0.171.239
  selector:
    role: nfs
  ports:
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP

---
kind: Pod
apiVersion: v1
metadata:
  name: nfs-server-pod
  labels:
    role: nfs
spec:
  containers:
    - name: nfs-server-container
      image: itsthenetwork/nfs-server-alpine:latest
      env:
      - name: SHARED_DIRECTORY
        value: "/exports"
      volumeMounts:
        - mountPath: /exports
          name: nfs-vol
      securityContext:
        privileged: true
  volumes:
    - name: nfs-vol
      emptyDir: {}
---