name: E2E Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      REGISTRY: k8s.gcr.io/sig-storage
      IMAGE_VERSION: ci-build
      IMAGE_NAME: nfsplugin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Build image
        run: |
          make build
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_VERSION .
      - uses: engineerd/setup-kind@v0.4.0
        name: Setting up KinD cluster
        with:
          version: "v0.9.0"
      - name: Push image to KinD
        run: |
          kind load docker-image --name=kind $REGISTRY/$IMAGE_NAME:$IMAGE_VERSION
      - name: Run E2E Tests
        run: |
          make e2e-test
          
